[project]
name = "bittensor-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bittensor>=9.12.1",
    "python-socks>=2.7.2",
]
